// Copyright Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	ScreenPixelShaderOES.usf: Filter pixel shader source.
=============================================================================*/

#include "Common.ush"

Texture2D InTexture;

SamplerState InTextureSampler;

void Main(
	FScreenVertexOutput Input,
	out float4 OutColor : SV_Target0
	)
{
    OutColor = InTexture.Sample(InTextureSampler, Input.UV);
}
